### ISSUE TITLE
FHE Proof: Separate Client and Server

### ISSUE THREAD

**Issue by Davide236** [Sunscreen-tech/Sunscreen#330]
I was wondering if it were possible to implement the FHE proof in a client-server architecture instead of keeping everything in the same file. I was wondering since all examples use a single-file structure to split the FHE between a Client and Server file how would that work?

I'm asking since I noticed that for FHE both the Client and Server objects (or Bob and Alice depending on the example), the Client has to access the Server object (since we need the Server to create the Client) and vice-versa. 

Is that something that cannot be done in the current state of the compiler or am I just approaching this wrongly?

**Comment by samtay** [comment]
It is certainly possible to have a legitimate client-server architecture using the current state of the compiler. The only information that has to be shared between parties are the parameters, the public key, and the program inputs/outputs - all of which are serializable.

Are you writing this in Rust? If so, an easy way to do this would be to have shared library code defining your FHE program `some_fhe_prog` (or a shared crate if you want to use a workspace), and then define two separate executables for `client` and `server` that can import the FHE program. What follows is mostly pseudocode but should be enough for you to get started.

### shared library code
```rust
#[fhe_program(scheme = "bfv")]
fn some_fhe_prog(a: Cipher<Signed>, b: Cipher<Signed>) -> Cipher<Signed> {
    a * b
}
```

### client code

```rust
fn main() -> Result<()> {
    let fhe_prog = some_fhe_prog.compile()?;
    let runtime = some_fhe_prog.runtime()?;

    let (public_key, private_key) = runtime.generate_keys()?;

    // You probably want to use the `Serialize` impl to save the keys here

    let a = runtime.encrypt(Signed::from(15), &public_key)?;
    let b = runtime.encrypt(Signed::from(5), &public_key)?;

    // Use the `Serialize` impls to send your ciphertexts and public key to the server, e.g.
    let payload = json!({
        public_key: public_key,
        arg_1: a,
        arg_2: b
    });
    
    let result: Ciphertext = reqwest::blocking::Client::new().post("server-address")
        .json(payload)
        .send()?
        .json()?;

    let c: Signed = runtime.decrypt(&result, &private_key)?;

    println!("{c}");
    Ok(())
}
```

### server code

```rust
fn main() -> Result<()> {
    /// spin up a web server using a popular library
    init_server_with_handler('/', handler);
}

fn handler(a: Ciphertext, b: Ciphertext, public_key: PublicKey) -> Result<Ciphertext> {
    let fhe_prog = some_fhe_prog.compile()?;
    let runtime = some_fhe_prog.runtime()?;
    let results = runtime.run(
         &fhe_prog,
         vec![a, b],
         &public_key
     )?;
    Ok(results[0])
}
```

**Comment by samtay** [comment]
@Davide236 I'm going to close this but feel free to ask more questions if you have any!
