### ISSUE TITLE
`sunscreen::Error` does not implement `std::error:Error`

### ISSUE THREAD

**Issue by flattte** [Sunscreen-tech/Sunscreen#336]
is there any reason why this type or actually any error types does not implement `std::error::Error`?

**Comment by samtay** [comment]
What version of sunscreen are you using? Our latest released version does have [`Error` impls](https://docs.rs/sunscreen/0.8.1/sunscreen/enum.Error.html#impl-Error-for-Error). If you were just looking through the code, these are generated provided by the [thiserror](https://docs.rs/thiserror/latest/thiserror/) derive macro.
