### ISSUE TITLE
Breaking out seal_fhe: repo and license

### ISSUE THREAD

**Issue by taqtiqa-mark** [Sunscreen-tech/Sunscreen#353]
Thanks for the effort put into the SEAL bindings.  

Would you be willing to make the SEAL bindings crate available under the typical Rust dual license of MIT or Apache 2?
If so would you accept a PR making the `seal_fhe` folder a sub-repo?

**Comment by rickwebiii** [comment]
We'll definitely consider this, thanks for the feedback!

**Comment by taqtiqa-mark** [comment]
Closing on the basis this can be reopened if the decision is to do so.
